name: Lint and test CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Run tests and linter
        run: yarn test-all
        env:
          NODE_OPTIONS: --openssl-legacy-provider
